// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxJ0QDzdc-tVh9fRHwlNkpj0Yg62MkTo8',
    appId: '1:712775517224:web:22bc60ff29f83e8ab9a11d',
    messagingSenderId: '712775517224',
    projectId: 'ars-user-3c08f',
    authDomain: 'ars-user-3c08f.firebaseapp.com',
    storageBucket: 'ars-user-3c08f.appspot.com',
    measurementId: 'G-6J560H47N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1FpVpQbp3NQQkgSHtPK_dyps5QviIzjs',
    appId: '1:712775517224:android:9383e1296dfda391b9a11d',
    messagingSenderId: '712775517224',
    projectId: 'ars-user-3c08f',
    storageBucket: 'ars-user-3c08f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgst76AkdrH1H28zLkZtWkxSu1B8JgK7w',
    appId: '1:712775517224:ios:dd87d3c1b3c2a03eb9a11d',
    messagingSenderId: '712775517224',
    projectId: 'ars-user-3c08f',
    storageBucket: 'ars-user-3c08f.appspot.com',
    iosClientId: '712775517224-15et18di85lqnfgadap7v08v64vl54tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ars',
  );
}
